services:
  mqtt_sky:
    command:
      - "python"
      - "./sky.py"
    container_name: "mqtt_sky"
    environment:
      - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "SKYREMOTE_IP=192.168.1.194"
      - "MOSQUITTO_IP=192.168.1.206"
      - "MOSQUITTO_PORT=1883"
    hostname: "mqtt_sky"
    image: "mqtt_sky"
    ipc: "private"
    logging:
      driver: "journald"
      options: {}
    network_mode: "bridge"
    restart: "unless-stopped"
    working_dir: "/"
version: "3.6"
